//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalycapGlobalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guia
    {
        public int Id { get; set; }
        public string NumGuia { get; set; }
        public int ClienteId { get; set; }
        public int PruductoId { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnit { get; set; }
        public decimal TotalNeto { get; set; }
        public decimal PorcDesc { get; set; }
        public decimal ValorDesc { get; set; }
        public decimal TotalEnvio { get; set; }
        public int AlmacenId { get; set; }
        public int VehiculoId { get; set; }
        public int OperadorId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int EstadoId { get; set; }
        public int TipoEnvioId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Operador Operador { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual TipoEnvio TipoEnvio { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
