//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalycapGlobalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operador()
        {
            this.Guias = new HashSet<Guia>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string NumDoc { get; set; }
        public int TipoDocId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guia> Guias { get; set; }
        public virtual TipoDoc TipoDoc { get; set; }
    }
}
