//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalycapGlobalWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pai", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Pai : object
    {
        
        private string CodAreaField;
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Region[] RegionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodArea
        {
            get
            {
                return this.CodAreaField;
            }
            set
            {
                this.CodAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Region[] Regions
        {
            get
            {
                return this.RegionsField;
            }
            set
            {
                this.RegionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Region : object
    {
        
        private TalycapGlobalWCF.Ciudad[] CiudadsField;
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Pai PaiField;
        
        private int PaisIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Ciudad[] Ciudads
        {
            get
            {
                return this.CiudadsField;
            }
            set
            {
                this.CiudadsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Pai Pai
        {
            get
            {
                return this.PaiField;
            }
            set
            {
                this.PaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisId
        {
            get
            {
                return this.PaisIdField;
            }
            set
            {
                this.PaisIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Ciudad : object
    {
        
        private TalycapGlobalWCF.Almacen[] AlmacensField;
        
        private TalycapGlobalWCF.Cliente[] ClientesField;
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Region RegionField;
        
        private int RegionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Almacen[] Almacens
        {
            get
            {
                return this.AlmacensField;
            }
            set
            {
                this.AlmacensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Cliente[] Clientes
        {
            get
            {
                return this.ClientesField;
            }
            set
            {
                this.ClientesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Region Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionId
        {
            get
            {
                return this.RegionIdField;
            }
            set
            {
                this.RegionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Almacen", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Almacen : object
    {
        
        private TalycapGlobalWCF.Ciudad CiudadField;
        
        private int CiudadIdField;
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Producto[] ProductoesField;
        
        private TalycapGlobalWCF.TipoAlmacen TipoAlmacenField;
        
        private int TipoAlmacenIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Ciudad Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadId
        {
            get
            {
                return this.CiudadIdField;
            }
            set
            {
                this.CiudadIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Producto[] Productoes
        {
            get
            {
                return this.ProductoesField;
            }
            set
            {
                this.ProductoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoAlmacen TipoAlmacen
        {
            get
            {
                return this.TipoAlmacenField;
            }
            set
            {
                this.TipoAlmacenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoAlmacenId
        {
            get
            {
                return this.TipoAlmacenIdField;
            }
            set
            {
                this.TipoAlmacenIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Cliente : object
    {
        
        private TalycapGlobalWCF.Ciudad CiudadField;
        
        private int CiudadIdField;
        
        private string DireccionField;
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string IndicativoField;
        
        private string NitField;
        
        private string NombreField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Ciudad Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadId
        {
            get
            {
                return this.CiudadIdField;
            }
            set
            {
                this.CiudadIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indicativo
        {
            get
            {
                return this.IndicativoField;
            }
            set
            {
                this.IndicativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nit
        {
            get
            {
                return this.NitField;
            }
            set
            {
                this.NitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAlmacen", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class TipoAlmacen : object
    {
        
        private TalycapGlobalWCF.Almacen[] AlmacensField;
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Almacen[] Almacens
        {
            get
            {
                return this.AlmacensField;
            }
            set
            {
                this.AlmacensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Producto : object
    {
        
        private TalycapGlobalWCF.Almacen AlmacenField;
        
        private int AlmacenIdField;
        
        private string CodRefField;
        
        private string DescripcionField;
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string NombreField;
        
        private decimal PrecioField;
        
        private TalycapGlobalWCF.TipoProducto TipoProductoField;
        
        private int TipoProductoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Almacen Almacen
        {
            get
            {
                return this.AlmacenField;
            }
            set
            {
                this.AlmacenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlmacenId
        {
            get
            {
                return this.AlmacenIdField;
            }
            set
            {
                this.AlmacenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRef
        {
            get
            {
                return this.CodRefField;
            }
            set
            {
                this.CodRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoProducto TipoProducto
        {
            get
            {
                return this.TipoProductoField;
            }
            set
            {
                this.TipoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoProductoId
        {
            get
            {
                return this.TipoProductoIdField;
            }
            set
            {
                this.TipoProductoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoProducto", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class TipoProducto : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Producto[] ProductoesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Producto[] Productoes
        {
            get
            {
                return this.ProductoesField;
            }
            set
            {
                this.ProductoesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guia", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Guia : object
    {
        
        private int AlmacenIdField;
        
        private int CantidadField;
        
        private TalycapGlobalWCF.Cliente ClienteField;
        
        private int ClienteIdField;
        
        private TalycapGlobalWCF.Estado EstadoField;
        
        private int EstadoIdField;
        
        private System.Nullable<System.DateTime> FechaEntregaField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdField;
        
        private string NumGuiaField;
        
        private TalycapGlobalWCF.Operador OperadorField;
        
        private int OperadorIdField;
        
        private decimal PorcDescField;
        
        private decimal PrecioUnitField;
        
        private TalycapGlobalWCF.Producto ProductoField;
        
        private int PruductoIdField;
        
        private TalycapGlobalWCF.TipoEnvio TipoEnvioField;
        
        private int TipoEnvioIdField;
        
        private decimal TotalEnvioField;
        
        private decimal TotalNetoField;
        
        private decimal ValorDescField;
        
        private TalycapGlobalWCF.Vehiculo VehiculoField;
        
        private int VehiculoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlmacenId
        {
            get
            {
                return this.AlmacenIdField;
            }
            set
            {
                this.AlmacenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Cliente Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId
        {
            get
            {
                return this.ClienteIdField;
            }
            set
            {
                this.ClienteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoId
        {
            get
            {
                return this.EstadoIdField;
            }
            set
            {
                this.EstadoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEntrega
        {
            get
            {
                return this.FechaEntregaField;
            }
            set
            {
                this.FechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumGuia
        {
            get
            {
                return this.NumGuiaField;
            }
            set
            {
                this.NumGuiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Operador Operador
        {
            get
            {
                return this.OperadorField;
            }
            set
            {
                this.OperadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperadorId
        {
            get
            {
                return this.OperadorIdField;
            }
            set
            {
                this.OperadorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcDesc
        {
            get
            {
                return this.PorcDescField;
            }
            set
            {
                this.PorcDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnit
        {
            get
            {
                return this.PrecioUnitField;
            }
            set
            {
                this.PrecioUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Producto Producto
        {
            get
            {
                return this.ProductoField;
            }
            set
            {
                this.ProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PruductoId
        {
            get
            {
                return this.PruductoIdField;
            }
            set
            {
                this.PruductoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoEnvio TipoEnvio
        {
            get
            {
                return this.TipoEnvioField;
            }
            set
            {
                this.TipoEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoEnvioId
        {
            get
            {
                return this.TipoEnvioIdField;
            }
            set
            {
                this.TipoEnvioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalEnvio
        {
            get
            {
                return this.TotalEnvioField;
            }
            set
            {
                this.TotalEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDesc
        {
            get
            {
                return this.ValorDescField;
            }
            set
            {
                this.ValorDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Vehiculo Vehiculo
        {
            get
            {
                return this.VehiculoField;
            }
            set
            {
                this.VehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoId
        {
            get
            {
                return this.VehiculoIdField;
            }
            set
            {
                this.VehiculoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Estado : object
    {
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operador", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Operador : object
    {
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string NombresField;
        
        private string NumDocField;
        
        private TalycapGlobalWCF.TipoDoc TipoDocField;
        
        private int TipoDocIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDoc
        {
            get
            {
                return this.NumDocField;
            }
            set
            {
                this.NumDocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoDoc TipoDoc
        {
            get
            {
                return this.TipoDocField;
            }
            set
            {
                this.TipoDocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocId
        {
            get
            {
                return this.TipoDocIdField;
            }
            set
            {
                this.TipoDocIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEnvio", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class TipoEnvio : object
    {
        
        private TalycapGlobalWCF.ConsecutivoGuia[] ConsecutivoGuiasField;
        
        private TalycapGlobalWCF.Descuento[] DescuentosField;
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.ConsecutivoGuia[] ConsecutivoGuias
        {
            get
            {
                return this.ConsecutivoGuiasField;
            }
            set
            {
                this.ConsecutivoGuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Descuento[] Descuentos
        {
            get
            {
                return this.DescuentosField;
            }
            set
            {
                this.DescuentosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Vehiculo : object
    {
        
        private string DescripcionField;
        
        private TalycapGlobalWCF.Guia[] GuiasField;
        
        private int IdField;
        
        private string MatriculaField;
        
        private TalycapGlobalWCF.TipoVehiculo TipoVehiculoField;
        
        private int TipoVehiculoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Guia[] Guias
        {
            get
            {
                return this.GuiasField;
            }
            set
            {
                this.GuiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula
        {
            get
            {
                return this.MatriculaField;
            }
            set
            {
                this.MatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoVehiculo TipoVehiculo
        {
            get
            {
                return this.TipoVehiculoField;
            }
            set
            {
                this.TipoVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoVehiculoId
        {
            get
            {
                return this.TipoVehiculoIdField;
            }
            set
            {
                this.TipoVehiculoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDoc", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class TipoDoc : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Operador[] OperadorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Operador[] Operadors
        {
            get
            {
                return this.OperadorsField;
            }
            set
            {
                this.OperadorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsecutivoGuia", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class ConsecutivoGuia : object
    {
        
        private string ConsecutivoField;
        
        private TalycapGlobalWCF.TipoEnvio TipoEnvioField;
        
        private int TipoEnvioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consecutivo
        {
            get
            {
                return this.ConsecutivoField;
            }
            set
            {
                this.ConsecutivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoEnvio TipoEnvio
        {
            get
            {
                return this.TipoEnvioField;
            }
            set
            {
                this.TipoEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoEnvioId
        {
            get
            {
                return this.TipoEnvioIdField;
            }
            set
            {
                this.TipoEnvioIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Descuento", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class Descuento : object
    {
        
        private int CantidadMaxField;
        
        private string DescripcionField;
        
        private int IdField;
        
        private TalycapGlobalWCF.TipoEnvio TipoEnvioField;
        
        private int TipoEnvioIdField;
        
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadMax
        {
            get
            {
                return this.CantidadMaxField;
            }
            set
            {
                this.CantidadMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.TipoEnvio TipoEnvio
        {
            get
            {
                return this.TipoEnvioField;
            }
            set
            {
                this.TipoEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoEnvioId
        {
            get
            {
                return this.TipoEnvioIdField;
            }
            set
            {
                this.TipoEnvioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoVehiculo", Namespace="http://schemas.datacontract.org/2004/07/TalycapGlobalData")]
    public partial class TipoVehiculo : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private TalycapGlobalWCF.Vehiculo[] VehiculoesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TalycapGlobalWCF.Vehiculo[] Vehiculoes
        {
            get
            {
                return this.VehiculoesField;
            }
            set
            {
                this.VehiculoesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TalycapGlobalWCF.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.CompositeType> GetDataUsingDataContractAsync(TalycapGlobalWCF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaPaises", ReplyAction="http://tempuri.org/IService/ListaPaisesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Pai[]> ListaPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPais", ReplyAction="http://tempuri.org/IService/GetPaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> GetPaisAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePais", ReplyAction="http://tempuri.org/IService/CreatePaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> CreatePaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPais", ReplyAction="http://tempuri.org/IService/EditPaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> EditPaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePais", ReplyAction="http://tempuri.org/IService/DeletePaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> DeletePaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaRegiones", ReplyAction="http://tempuri.org/IService/ListaRegionesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Region[]> ListaRegionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRegion", ReplyAction="http://tempuri.org/IService/GetRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Region> GetRegionAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateRegion", ReplyAction="http://tempuri.org/IService/CreateRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Region> CreateRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditRegion", ReplyAction="http://tempuri.org/IService/EditRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Region> EditRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteRegion", ReplyAction="http://tempuri.org/IService/DeleteRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Region> DeleteRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaCiudades", ReplyAction="http://tempuri.org/IService/ListaCiudadesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad[]> ListaCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCiudad", ReplyAction="http://tempuri.org/IService/GetCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> GetCiudadAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCiudad", ReplyAction="http://tempuri.org/IService/CreateCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> CreateCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCiudad", ReplyAction="http://tempuri.org/IService/EditCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> EditCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCiudad", ReplyAction="http://tempuri.org/IService/DeleteCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> DeleteCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoAlmacen", ReplyAction="http://tempuri.org/IService/ListaTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen[]> ListaTipoAlmacenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoAlmacen", ReplyAction="http://tempuri.org/IService/GetTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> GetTipoAlmacenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoAlmacen", ReplyAction="http://tempuri.org/IService/CreateTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> CreateTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoAlmacen", ReplyAction="http://tempuri.org/IService/EditTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> EditTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoAlmacen", ReplyAction="http://tempuri.org/IService/DeleteTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> DeleteTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoProductos", ReplyAction="http://tempuri.org/IService/ListaTipoProductosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto[]> ListaTipoProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoProducto", ReplyAction="http://tempuri.org/IService/GetTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> GetTipoProductoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoProducto", ReplyAction="http://tempuri.org/IService/CreateTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> CreateTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoProducto", ReplyAction="http://tempuri.org/IService/EditTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> EditTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoProducto", ReplyAction="http://tempuri.org/IService/DeleteTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> DeleteTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoEnvios", ReplyAction="http://tempuri.org/IService/ListaTipoEnviosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio[]> ListaTipoEnviosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoEnvio", ReplyAction="http://tempuri.org/IService/GetTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> GetTipoEnvioAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoEnvio", ReplyAction="http://tempuri.org/IService/CreateTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> CreateTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoEnvio", ReplyAction="http://tempuri.org/IService/EditTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> EditTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoEnvio", ReplyAction="http://tempuri.org/IService/DeleteTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> DeleteTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoDocs", ReplyAction="http://tempuri.org/IService/ListaTipoDocsResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc[]> ListaTipoDocsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoDoc", ReplyAction="http://tempuri.org/IService/GetTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> GetTipoDocAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoDoc", ReplyAction="http://tempuri.org/IService/CreateTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> CreateTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoDoc", ReplyAction="http://tempuri.org/IService/EditTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> EditTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoDoc", ReplyAction="http://tempuri.org/IService/DeleteTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> DeleteTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoVehiculos", ReplyAction="http://tempuri.org/IService/ListaTipoVehiculosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo[]> ListaTipoVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoVehiculo", ReplyAction="http://tempuri.org/IService/GetTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> GetTipoVehiculoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoVehiculo", ReplyAction="http://tempuri.org/IService/CreateTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> CreateTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoVehiculo", ReplyAction="http://tempuri.org/IService/EditTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> EditTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoVehiculo", ReplyAction="http://tempuri.org/IService/DeleteTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> DeleteTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaEstados", ReplyAction="http://tempuri.org/IService/ListaEstadosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Estado[]> ListaEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEstado", ReplyAction="http://tempuri.org/IService/GetEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> GetEstadoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEstado", ReplyAction="http://tempuri.org/IService/CreateEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> CreateEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditEstado", ReplyAction="http://tempuri.org/IService/EditEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> EditEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteEstado", ReplyAction="http://tempuri.org/IService/DeleteEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> DeleteEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetConsecutivo", ReplyAction="http://tempuri.org/IService/GetConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> GetConsecutivoAsync(int TipoEnvioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateConsecutivo", ReplyAction="http://tempuri.org/IService/CreateConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> CreateConsecutivoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditConsecutivo", ReplyAction="http://tempuri.org/IService/EditConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> EditConsecutivoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaAlmacenes", ReplyAction="http://tempuri.org/IService/ListaAlmacenesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen[]> ListaAlmacenesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlmacen", ReplyAction="http://tempuri.org/IService/GetAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> GetAlmacenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAlmacen", ReplyAction="http://tempuri.org/IService/CreateAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> CreateAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditAlmacen", ReplyAction="http://tempuri.org/IService/EditAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> EditAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAlmacen", ReplyAction="http://tempuri.org/IService/DeleteAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> DeleteAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaProductos", ReplyAction="http://tempuri.org/IService/ListaProductosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Producto[]> ListaProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProducto", ReplyAction="http://tempuri.org/IService/GetProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> GetProductoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProducto", ReplyAction="http://tempuri.org/IService/CreateProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> CreateProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProducto", ReplyAction="http://tempuri.org/IService/EditProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> EditProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProducto", ReplyAction="http://tempuri.org/IService/DeleteProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> DeleteProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaDescuentos", ReplyAction="http://tempuri.org/IService/ListaDescuentosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento[]> ListaDescuentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDescuento", ReplyAction="http://tempuri.org/IService/GetDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> GetDescuentoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateDescuento", ReplyAction="http://tempuri.org/IService/CreateDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> CreateDescuentoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditDescuento", ReplyAction="http://tempuri.org/IService/EditDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> EditDescuentoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDescuento", ReplyAction="http://tempuri.org/IService/DeleteDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> DeleteDescuentoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaOperadores", ReplyAction="http://tempuri.org/IService/ListaOperadoresResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Operador[]> ListaOperadoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperador", ReplyAction="http://tempuri.org/IService/GetOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> GetOperadorAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateOperador", ReplyAction="http://tempuri.org/IService/CreateOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> CreateOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditOperador", ReplyAction="http://tempuri.org/IService/EditOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> EditOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperador", ReplyAction="http://tempuri.org/IService/DeleteOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> DeleteOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaVehiculos", ReplyAction="http://tempuri.org/IService/ListaVehiculosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo[]> ListaVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVehiculo", ReplyAction="http://tempuri.org/IService/GetVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> GetVehiculoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateVehiculo", ReplyAction="http://tempuri.org/IService/CreateVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> CreateVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditVehiculo", ReplyAction="http://tempuri.org/IService/EditVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> EditVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteVehiculo", ReplyAction="http://tempuri.org/IService/DeleteVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> DeleteVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaGuias", ReplyAction="http://tempuri.org/IService/ListaGuiasResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Guia[]> ListaGuiasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGuia", ReplyAction="http://tempuri.org/IService/GetGuiaResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Guia> GetGuiaAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGuia", ReplyAction="http://tempuri.org/IService/CreateGuiaResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Guia> CreateGuiaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaClientes", ReplyAction="http://tempuri.org/IService/ListaClientesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente[]> ListaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCliente", ReplyAction="http://tempuri.org/IService/GetClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> GetClienteAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCliente", ReplyAction="http://tempuri.org/IService/CreateClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> CreateClienteAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCliente", ReplyAction="http://tempuri.org/IService/EditClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> EditClienteAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCliente", ReplyAction="http://tempuri.org/IService/DeleteClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> DeleteClienteAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceChannel : TalycapGlobalWCF.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TalycapGlobalWCF.IService>, TalycapGlobalWCF.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.CompositeType> GetDataUsingDataContractAsync(TalycapGlobalWCF.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Pai[]> ListaPaisesAsync()
        {
            return base.Channel.ListaPaisesAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> GetPaisAsync(int Id)
        {
            return base.Channel.GetPaisAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> CreatePaisAsync(string json)
        {
            return base.Channel.CreatePaisAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> EditPaisAsync(string json)
        {
            return base.Channel.EditPaisAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Pai> DeletePaisAsync(string json)
        {
            return base.Channel.DeletePaisAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Region[]> ListaRegionesAsync()
        {
            return base.Channel.ListaRegionesAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Region> GetRegionAsync(int Id)
        {
            return base.Channel.GetRegionAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Region> CreateRegionAsync(string json)
        {
            return base.Channel.CreateRegionAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Region> EditRegionAsync(string json)
        {
            return base.Channel.EditRegionAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Region> DeleteRegionAsync(string json)
        {
            return base.Channel.DeleteRegionAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad[]> ListaCiudadesAsync()
        {
            return base.Channel.ListaCiudadesAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> GetCiudadAsync(int Id)
        {
            return base.Channel.GetCiudadAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> CreateCiudadAsync(string json)
        {
            return base.Channel.CreateCiudadAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> EditCiudadAsync(string json)
        {
            return base.Channel.EditCiudadAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Ciudad> DeleteCiudadAsync(string json)
        {
            return base.Channel.DeleteCiudadAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen[]> ListaTipoAlmacenAsync()
        {
            return base.Channel.ListaTipoAlmacenAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> GetTipoAlmacenAsync(int Id)
        {
            return base.Channel.GetTipoAlmacenAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> CreateTipoAlmacenAsync(string json)
        {
            return base.Channel.CreateTipoAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> EditTipoAlmacenAsync(string json)
        {
            return base.Channel.EditTipoAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoAlmacen> DeleteTipoAlmacenAsync(string json)
        {
            return base.Channel.DeleteTipoAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto[]> ListaTipoProductosAsync()
        {
            return base.Channel.ListaTipoProductosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> GetTipoProductoAsync(int Id)
        {
            return base.Channel.GetTipoProductoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> CreateTipoProductoAsync(string json)
        {
            return base.Channel.CreateTipoProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> EditTipoProductoAsync(string json)
        {
            return base.Channel.EditTipoProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoProducto> DeleteTipoProductoAsync(string json)
        {
            return base.Channel.DeleteTipoProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio[]> ListaTipoEnviosAsync()
        {
            return base.Channel.ListaTipoEnviosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> GetTipoEnvioAsync(int Id)
        {
            return base.Channel.GetTipoEnvioAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> CreateTipoEnvioAsync(string json)
        {
            return base.Channel.CreateTipoEnvioAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> EditTipoEnvioAsync(string json)
        {
            return base.Channel.EditTipoEnvioAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoEnvio> DeleteTipoEnvioAsync(string json)
        {
            return base.Channel.DeleteTipoEnvioAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc[]> ListaTipoDocsAsync()
        {
            return base.Channel.ListaTipoDocsAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> GetTipoDocAsync(int Id)
        {
            return base.Channel.GetTipoDocAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> CreateTipoDocAsync(string json)
        {
            return base.Channel.CreateTipoDocAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> EditTipoDocAsync(string json)
        {
            return base.Channel.EditTipoDocAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoDoc> DeleteTipoDocAsync(string json)
        {
            return base.Channel.DeleteTipoDocAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo[]> ListaTipoVehiculosAsync()
        {
            return base.Channel.ListaTipoVehiculosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> GetTipoVehiculoAsync(int Id)
        {
            return base.Channel.GetTipoVehiculoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> CreateTipoVehiculoAsync(string json)
        {
            return base.Channel.CreateTipoVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> EditTipoVehiculoAsync(string json)
        {
            return base.Channel.EditTipoVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.TipoVehiculo> DeleteTipoVehiculoAsync(string json)
        {
            return base.Channel.DeleteTipoVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Estado[]> ListaEstadosAsync()
        {
            return base.Channel.ListaEstadosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> GetEstadoAsync(int Id)
        {
            return base.Channel.GetEstadoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> CreateEstadoAsync(string json)
        {
            return base.Channel.CreateEstadoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> EditEstadoAsync(string json)
        {
            return base.Channel.EditEstadoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Estado> DeleteEstadoAsync(string json)
        {
            return base.Channel.DeleteEstadoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> GetConsecutivoAsync(int TipoEnvioId)
        {
            return base.Channel.GetConsecutivoAsync(TipoEnvioId);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> CreateConsecutivoAsync(string json)
        {
            return base.Channel.CreateConsecutivoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.ConsecutivoGuia> EditConsecutivoAsync(string json)
        {
            return base.Channel.EditConsecutivoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen[]> ListaAlmacenesAsync()
        {
            return base.Channel.ListaAlmacenesAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> GetAlmacenAsync(int Id)
        {
            return base.Channel.GetAlmacenAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> CreateAlmacenAsync(string json)
        {
            return base.Channel.CreateAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> EditAlmacenAsync(string json)
        {
            return base.Channel.EditAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Almacen> DeleteAlmacenAsync(string json)
        {
            return base.Channel.DeleteAlmacenAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Producto[]> ListaProductosAsync()
        {
            return base.Channel.ListaProductosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> GetProductoAsync(int Id)
        {
            return base.Channel.GetProductoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> CreateProductoAsync(string json)
        {
            return base.Channel.CreateProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> EditProductoAsync(string json)
        {
            return base.Channel.EditProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Producto> DeleteProductoAsync(string json)
        {
            return base.Channel.DeleteProductoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento[]> ListaDescuentosAsync()
        {
            return base.Channel.ListaDescuentosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> GetDescuentoAsync(int Id)
        {
            return base.Channel.GetDescuentoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> CreateDescuentoAsync(string json)
        {
            return base.Channel.CreateDescuentoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> EditDescuentoAsync(string json)
        {
            return base.Channel.EditDescuentoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Descuento> DeleteDescuentoAsync(string json)
        {
            return base.Channel.DeleteDescuentoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Operador[]> ListaOperadoresAsync()
        {
            return base.Channel.ListaOperadoresAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> GetOperadorAsync(int Id)
        {
            return base.Channel.GetOperadorAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> CreateOperadorAsync(string json)
        {
            return base.Channel.CreateOperadorAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> EditOperadorAsync(string json)
        {
            return base.Channel.EditOperadorAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Operador> DeleteOperadorAsync(string json)
        {
            return base.Channel.DeleteOperadorAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo[]> ListaVehiculosAsync()
        {
            return base.Channel.ListaVehiculosAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> GetVehiculoAsync(int Id)
        {
            return base.Channel.GetVehiculoAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> CreateVehiculoAsync(string json)
        {
            return base.Channel.CreateVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> EditVehiculoAsync(string json)
        {
            return base.Channel.EditVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Vehiculo> DeleteVehiculoAsync(string json)
        {
            return base.Channel.DeleteVehiculoAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Guia[]> ListaGuiasAsync()
        {
            return base.Channel.ListaGuiasAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Guia> GetGuiaAsync(int Id)
        {
            return base.Channel.GetGuiaAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Guia> CreateGuiaAsync(string json)
        {
            return base.Channel.CreateGuiaAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente[]> ListaClientesAsync()
        {
            return base.Channel.ListaClientesAsync();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> GetClienteAsync(int Id)
        {
            return base.Channel.GetClienteAsync(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> CreateClienteAsync(string json)
        {
            return base.Channel.CreateClienteAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> EditClienteAsync(string json)
        {
            return base.Channel.EditClienteAsync(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalWCF.Cliente> DeleteClienteAsync(string json)
        {
            return base.Channel.DeleteClienteAsync(json);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51454/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
