//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalycapGlobalTestUnit.TalycapGlobalWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TalycapGlobalWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDescuento", ReplyAction="http://tempuri.org/IService/DeleteDescuentoResponse")]
        TalycapGlobalData.Descuento DeleteDescuento(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteDescuento", ReplyAction="http://tempuri.org/IService/DeleteDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Descuento> DeleteDescuentoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaOperadores", ReplyAction="http://tempuri.org/IService/ListaOperadoresResponse")]
        TalycapGlobalData.Operador[] ListaOperadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaOperadores", ReplyAction="http://tempuri.org/IService/ListaOperadoresResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Operador[]> ListaOperadoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperador", ReplyAction="http://tempuri.org/IService/GetOperadorResponse")]
        TalycapGlobalData.Operador GetOperador(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOperador", ReplyAction="http://tempuri.org/IService/GetOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Operador> GetOperadorAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateOperador", ReplyAction="http://tempuri.org/IService/CreateOperadorResponse")]
        TalycapGlobalData.Operador CreateOperador(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateOperador", ReplyAction="http://tempuri.org/IService/CreateOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Operador> CreateOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditOperador", ReplyAction="http://tempuri.org/IService/EditOperadorResponse")]
        TalycapGlobalData.Operador EditOperador(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditOperador", ReplyAction="http://tempuri.org/IService/EditOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Operador> EditOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperador", ReplyAction="http://tempuri.org/IService/DeleteOperadorResponse")]
        TalycapGlobalData.Operador DeleteOperador(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteOperador", ReplyAction="http://tempuri.org/IService/DeleteOperadorResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Operador> DeleteOperadorAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaVehiculos", ReplyAction="http://tempuri.org/IService/ListaVehiculosResponse")]
        TalycapGlobalData.Vehiculo[] ListaVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaVehiculos", ReplyAction="http://tempuri.org/IService/ListaVehiculosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo[]> ListaVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVehiculo", ReplyAction="http://tempuri.org/IService/GetVehiculoResponse")]
        TalycapGlobalData.Vehiculo GetVehiculo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVehiculo", ReplyAction="http://tempuri.org/IService/GetVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> GetVehiculoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateVehiculo", ReplyAction="http://tempuri.org/IService/CreateVehiculoResponse")]
        TalycapGlobalData.Vehiculo CreateVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateVehiculo", ReplyAction="http://tempuri.org/IService/CreateVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> CreateVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditVehiculo", ReplyAction="http://tempuri.org/IService/EditVehiculoResponse")]
        TalycapGlobalData.Vehiculo EditVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditVehiculo", ReplyAction="http://tempuri.org/IService/EditVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> EditVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteVehiculo", ReplyAction="http://tempuri.org/IService/DeleteVehiculoResponse")]
        TalycapGlobalData.Vehiculo DeleteVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteVehiculo", ReplyAction="http://tempuri.org/IService/DeleteVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> DeleteVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaGuias", ReplyAction="http://tempuri.org/IService/ListaGuiasResponse")]
        TalycapGlobalData.Guia[] ListaGuias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaGuias", ReplyAction="http://tempuri.org/IService/ListaGuiasResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Guia[]> ListaGuiasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGuia", ReplyAction="http://tempuri.org/IService/GetGuiaResponse")]
        TalycapGlobalData.Guia GetGuia(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGuia", ReplyAction="http://tempuri.org/IService/GetGuiaResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Guia> GetGuiaAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGuia", ReplyAction="http://tempuri.org/IService/CreateGuiaResponse")]
        TalycapGlobalData.Guia CreateGuia(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGuia", ReplyAction="http://tempuri.org/IService/CreateGuiaResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Guia> CreateGuiaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaClientes", ReplyAction="http://tempuri.org/IService/ListaClientesResponse")]
        TalycapGlobalData.Cliente[] ListaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaClientes", ReplyAction="http://tempuri.org/IService/ListaClientesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Cliente[]> ListaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCliente", ReplyAction="http://tempuri.org/IService/GetClienteResponse")]
        TalycapGlobalData.Cliente GetCliente(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCliente", ReplyAction="http://tempuri.org/IService/GetClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Cliente> GetClienteAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCliente", ReplyAction="http://tempuri.org/IService/CreateClienteResponse")]
        TalycapGlobalData.Cliente CreateCliente(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCliente", ReplyAction="http://tempuri.org/IService/CreateClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Cliente> CreateClienteAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCliente", ReplyAction="http://tempuri.org/IService/EditClienteResponse")]
        TalycapGlobalData.Cliente EditCliente(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCliente", ReplyAction="http://tempuri.org/IService/EditClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Cliente> EditClienteAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCliente", ReplyAction="http://tempuri.org/IService/DeleteClienteResponse")]
        TalycapGlobalData.Cliente DeleteCliente(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCliente", ReplyAction="http://tempuri.org/IService/DeleteClienteResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Cliente> DeleteClienteAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType GetDataUsingDataContract(TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType> GetDataUsingDataContractAsync(TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaPaises", ReplyAction="http://tempuri.org/IService/ListaPaisesResponse")]
        TalycapGlobalData.Pai[] ListaPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaPaises", ReplyAction="http://tempuri.org/IService/ListaPaisesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Pai[]> ListaPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPais", ReplyAction="http://tempuri.org/IService/GetPaisResponse")]
        TalycapGlobalData.Pai GetPais(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPais", ReplyAction="http://tempuri.org/IService/GetPaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Pai> GetPaisAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePais", ReplyAction="http://tempuri.org/IService/CreatePaisResponse")]
        TalycapGlobalData.Pai CreatePais(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePais", ReplyAction="http://tempuri.org/IService/CreatePaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Pai> CreatePaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPais", ReplyAction="http://tempuri.org/IService/EditPaisResponse")]
        TalycapGlobalData.Pai EditPais(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPais", ReplyAction="http://tempuri.org/IService/EditPaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Pai> EditPaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePais", ReplyAction="http://tempuri.org/IService/DeletePaisResponse")]
        TalycapGlobalData.Pai DeletePais(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePais", ReplyAction="http://tempuri.org/IService/DeletePaisResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Pai> DeletePaisAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaRegiones", ReplyAction="http://tempuri.org/IService/ListaRegionesResponse")]
        TalycapGlobalData.Region[] ListaRegiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaRegiones", ReplyAction="http://tempuri.org/IService/ListaRegionesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Region[]> ListaRegionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRegion", ReplyAction="http://tempuri.org/IService/GetRegionResponse")]
        TalycapGlobalData.Region GetRegion(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRegion", ReplyAction="http://tempuri.org/IService/GetRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Region> GetRegionAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateRegion", ReplyAction="http://tempuri.org/IService/CreateRegionResponse")]
        TalycapGlobalData.Region CreateRegion(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateRegion", ReplyAction="http://tempuri.org/IService/CreateRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Region> CreateRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditRegion", ReplyAction="http://tempuri.org/IService/EditRegionResponse")]
        TalycapGlobalData.Region EditRegion(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditRegion", ReplyAction="http://tempuri.org/IService/EditRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Region> EditRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteRegion", ReplyAction="http://tempuri.org/IService/DeleteRegionResponse")]
        TalycapGlobalData.Region DeleteRegion(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteRegion", ReplyAction="http://tempuri.org/IService/DeleteRegionResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Region> DeleteRegionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaCiudades", ReplyAction="http://tempuri.org/IService/ListaCiudadesResponse")]
        TalycapGlobalData.Ciudad[] ListaCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaCiudades", ReplyAction="http://tempuri.org/IService/ListaCiudadesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Ciudad[]> ListaCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCiudad", ReplyAction="http://tempuri.org/IService/GetCiudadResponse")]
        TalycapGlobalData.Ciudad GetCiudad(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCiudad", ReplyAction="http://tempuri.org/IService/GetCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> GetCiudadAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCiudad", ReplyAction="http://tempuri.org/IService/CreateCiudadResponse")]
        TalycapGlobalData.Ciudad CreateCiudad(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateCiudad", ReplyAction="http://tempuri.org/IService/CreateCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> CreateCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCiudad", ReplyAction="http://tempuri.org/IService/EditCiudadResponse")]
        TalycapGlobalData.Ciudad EditCiudad(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCiudad", ReplyAction="http://tempuri.org/IService/EditCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> EditCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCiudad", ReplyAction="http://tempuri.org/IService/DeleteCiudadResponse")]
        TalycapGlobalData.Ciudad DeleteCiudad(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteCiudad", ReplyAction="http://tempuri.org/IService/DeleteCiudadResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> DeleteCiudadAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoAlmacen", ReplyAction="http://tempuri.org/IService/ListaTipoAlmacenResponse")]
        TalycapGlobalData.TipoAlmacen[] ListaTipoAlmacen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoAlmacen", ReplyAction="http://tempuri.org/IService/ListaTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen[]> ListaTipoAlmacenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoAlmacen", ReplyAction="http://tempuri.org/IService/GetTipoAlmacenResponse")]
        TalycapGlobalData.TipoAlmacen GetTipoAlmacen(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoAlmacen", ReplyAction="http://tempuri.org/IService/GetTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> GetTipoAlmacenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoAlmacen", ReplyAction="http://tempuri.org/IService/CreateTipoAlmacenResponse")]
        TalycapGlobalData.TipoAlmacen CreateTipoAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoAlmacen", ReplyAction="http://tempuri.org/IService/CreateTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> CreateTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoAlmacen", ReplyAction="http://tempuri.org/IService/EditTipoAlmacenResponse")]
        TalycapGlobalData.TipoAlmacen EditTipoAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoAlmacen", ReplyAction="http://tempuri.org/IService/EditTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> EditTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoAlmacen", ReplyAction="http://tempuri.org/IService/DeleteTipoAlmacenResponse")]
        TalycapGlobalData.TipoAlmacen DeleteTipoAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoAlmacen", ReplyAction="http://tempuri.org/IService/DeleteTipoAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> DeleteTipoAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoProductos", ReplyAction="http://tempuri.org/IService/ListaTipoProductosResponse")]
        TalycapGlobalData.TipoProducto[] ListaTipoProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoProductos", ReplyAction="http://tempuri.org/IService/ListaTipoProductosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto[]> ListaTipoProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoProducto", ReplyAction="http://tempuri.org/IService/GetTipoProductoResponse")]
        TalycapGlobalData.TipoProducto GetTipoProducto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoProducto", ReplyAction="http://tempuri.org/IService/GetTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> GetTipoProductoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoProducto", ReplyAction="http://tempuri.org/IService/CreateTipoProductoResponse")]
        TalycapGlobalData.TipoProducto CreateTipoProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoProducto", ReplyAction="http://tempuri.org/IService/CreateTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> CreateTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoProducto", ReplyAction="http://tempuri.org/IService/EditTipoProductoResponse")]
        TalycapGlobalData.TipoProducto EditTipoProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoProducto", ReplyAction="http://tempuri.org/IService/EditTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> EditTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoProducto", ReplyAction="http://tempuri.org/IService/DeleteTipoProductoResponse")]
        TalycapGlobalData.TipoProducto DeleteTipoProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoProducto", ReplyAction="http://tempuri.org/IService/DeleteTipoProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> DeleteTipoProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoEnvios", ReplyAction="http://tempuri.org/IService/ListaTipoEnviosResponse")]
        TalycapGlobalData.TipoEnvio[] ListaTipoEnvios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoEnvios", ReplyAction="http://tempuri.org/IService/ListaTipoEnviosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio[]> ListaTipoEnviosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoEnvio", ReplyAction="http://tempuri.org/IService/GetTipoEnvioResponse")]
        TalycapGlobalData.TipoEnvio GetTipoEnvio(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoEnvio", ReplyAction="http://tempuri.org/IService/GetTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> GetTipoEnvioAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoEnvio", ReplyAction="http://tempuri.org/IService/CreateTipoEnvioResponse")]
        TalycapGlobalData.TipoEnvio CreateTipoEnvio(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoEnvio", ReplyAction="http://tempuri.org/IService/CreateTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> CreateTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoEnvio", ReplyAction="http://tempuri.org/IService/EditTipoEnvioResponse")]
        TalycapGlobalData.TipoEnvio EditTipoEnvio(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoEnvio", ReplyAction="http://tempuri.org/IService/EditTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> EditTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoEnvio", ReplyAction="http://tempuri.org/IService/DeleteTipoEnvioResponse")]
        TalycapGlobalData.TipoEnvio DeleteTipoEnvio(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoEnvio", ReplyAction="http://tempuri.org/IService/DeleteTipoEnvioResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> DeleteTipoEnvioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoDocs", ReplyAction="http://tempuri.org/IService/ListaTipoDocsResponse")]
        TalycapGlobalData.TipoDoc[] ListaTipoDocs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoDocs", ReplyAction="http://tempuri.org/IService/ListaTipoDocsResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc[]> ListaTipoDocsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoDoc", ReplyAction="http://tempuri.org/IService/GetTipoDocResponse")]
        TalycapGlobalData.TipoDoc GetTipoDoc(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoDoc", ReplyAction="http://tempuri.org/IService/GetTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> GetTipoDocAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoDoc", ReplyAction="http://tempuri.org/IService/CreateTipoDocResponse")]
        TalycapGlobalData.TipoDoc CreateTipoDoc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoDoc", ReplyAction="http://tempuri.org/IService/CreateTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> CreateTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoDoc", ReplyAction="http://tempuri.org/IService/EditTipoDocResponse")]
        TalycapGlobalData.TipoDoc EditTipoDoc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoDoc", ReplyAction="http://tempuri.org/IService/EditTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> EditTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoDoc", ReplyAction="http://tempuri.org/IService/DeleteTipoDocResponse")]
        TalycapGlobalData.TipoDoc DeleteTipoDoc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoDoc", ReplyAction="http://tempuri.org/IService/DeleteTipoDocResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> DeleteTipoDocAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoVehiculos", ReplyAction="http://tempuri.org/IService/ListaTipoVehiculosResponse")]
        TalycapGlobalData.TipoVehiculo[] ListaTipoVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaTipoVehiculos", ReplyAction="http://tempuri.org/IService/ListaTipoVehiculosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo[]> ListaTipoVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoVehiculo", ReplyAction="http://tempuri.org/IService/GetTipoVehiculoResponse")]
        TalycapGlobalData.TipoVehiculo GetTipoVehiculo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTipoVehiculo", ReplyAction="http://tempuri.org/IService/GetTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> GetTipoVehiculoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoVehiculo", ReplyAction="http://tempuri.org/IService/CreateTipoVehiculoResponse")]
        TalycapGlobalData.TipoVehiculo CreateTipoVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTipoVehiculo", ReplyAction="http://tempuri.org/IService/CreateTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> CreateTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoVehiculo", ReplyAction="http://tempuri.org/IService/EditTipoVehiculoResponse")]
        TalycapGlobalData.TipoVehiculo EditTipoVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTipoVehiculo", ReplyAction="http://tempuri.org/IService/EditTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> EditTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoVehiculo", ReplyAction="http://tempuri.org/IService/DeleteTipoVehiculoResponse")]
        TalycapGlobalData.TipoVehiculo DeleteTipoVehiculo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTipoVehiculo", ReplyAction="http://tempuri.org/IService/DeleteTipoVehiculoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> DeleteTipoVehiculoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaEstados", ReplyAction="http://tempuri.org/IService/ListaEstadosResponse")]
        TalycapGlobalData.Estado[] ListaEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaEstados", ReplyAction="http://tempuri.org/IService/ListaEstadosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Estado[]> ListaEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEstado", ReplyAction="http://tempuri.org/IService/GetEstadoResponse")]
        TalycapGlobalData.Estado GetEstado(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEstado", ReplyAction="http://tempuri.org/IService/GetEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Estado> GetEstadoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEstado", ReplyAction="http://tempuri.org/IService/CreateEstadoResponse")]
        TalycapGlobalData.Estado CreateEstado(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEstado", ReplyAction="http://tempuri.org/IService/CreateEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Estado> CreateEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditEstado", ReplyAction="http://tempuri.org/IService/EditEstadoResponse")]
        TalycapGlobalData.Estado EditEstado(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditEstado", ReplyAction="http://tempuri.org/IService/EditEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Estado> EditEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteEstado", ReplyAction="http://tempuri.org/IService/DeleteEstadoResponse")]
        TalycapGlobalData.Estado DeleteEstado(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteEstado", ReplyAction="http://tempuri.org/IService/DeleteEstadoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Estado> DeleteEstadoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetConsecutivo", ReplyAction="http://tempuri.org/IService/GetConsecutivoResponse")]
        TalycapGlobalData.ConsecutivoGuia GetConsecutivo(int TipoEnvioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetConsecutivo", ReplyAction="http://tempuri.org/IService/GetConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> GetConsecutivoAsync(int TipoEnvioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateConsecutivo", ReplyAction="http://tempuri.org/IService/CreateConsecutivoResponse")]
        TalycapGlobalData.ConsecutivoGuia CreateConsecutivo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateConsecutivo", ReplyAction="http://tempuri.org/IService/CreateConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> CreateConsecutivoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditConsecutivo", ReplyAction="http://tempuri.org/IService/EditConsecutivoResponse")]
        TalycapGlobalData.ConsecutivoGuia EditConsecutivo(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditConsecutivo", ReplyAction="http://tempuri.org/IService/EditConsecutivoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> EditConsecutivoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaAlmacenes", ReplyAction="http://tempuri.org/IService/ListaAlmacenesResponse")]
        TalycapGlobalData.Almacen[] ListaAlmacenes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaAlmacenes", ReplyAction="http://tempuri.org/IService/ListaAlmacenesResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Almacen[]> ListaAlmacenesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlmacen", ReplyAction="http://tempuri.org/IService/GetAlmacenResponse")]
        TalycapGlobalData.Almacen GetAlmacen(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlmacen", ReplyAction="http://tempuri.org/IService/GetAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Almacen> GetAlmacenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAlmacen", ReplyAction="http://tempuri.org/IService/CreateAlmacenResponse")]
        TalycapGlobalData.Almacen CreateAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAlmacen", ReplyAction="http://tempuri.org/IService/CreateAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Almacen> CreateAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditAlmacen", ReplyAction="http://tempuri.org/IService/EditAlmacenResponse")]
        TalycapGlobalData.Almacen EditAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditAlmacen", ReplyAction="http://tempuri.org/IService/EditAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Almacen> EditAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAlmacen", ReplyAction="http://tempuri.org/IService/DeleteAlmacenResponse")]
        TalycapGlobalData.Almacen DeleteAlmacen(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAlmacen", ReplyAction="http://tempuri.org/IService/DeleteAlmacenResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Almacen> DeleteAlmacenAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaProductos", ReplyAction="http://tempuri.org/IService/ListaProductosResponse")]
        TalycapGlobalData.Producto[] ListaProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaProductos", ReplyAction="http://tempuri.org/IService/ListaProductosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Producto[]> ListaProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProducto", ReplyAction="http://tempuri.org/IService/GetProductoResponse")]
        TalycapGlobalData.Producto GetProducto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProducto", ReplyAction="http://tempuri.org/IService/GetProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Producto> GetProductoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProducto", ReplyAction="http://tempuri.org/IService/CreateProductoResponse")]
        TalycapGlobalData.Producto CreateProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProducto", ReplyAction="http://tempuri.org/IService/CreateProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Producto> CreateProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProducto", ReplyAction="http://tempuri.org/IService/EditProductoResponse")]
        TalycapGlobalData.Producto EditProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditProducto", ReplyAction="http://tempuri.org/IService/EditProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Producto> EditProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProducto", ReplyAction="http://tempuri.org/IService/DeleteProductoResponse")]
        TalycapGlobalData.Producto DeleteProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProducto", ReplyAction="http://tempuri.org/IService/DeleteProductoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Producto> DeleteProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaDescuentos", ReplyAction="http://tempuri.org/IService/ListaDescuentosResponse")]
        TalycapGlobalData.Descuento[] ListaDescuentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListaDescuentos", ReplyAction="http://tempuri.org/IService/ListaDescuentosResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Descuento[]> ListaDescuentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDescuento", ReplyAction="http://tempuri.org/IService/GetDescuentoResponse")]
        TalycapGlobalData.Descuento GetDescuento(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDescuento", ReplyAction="http://tempuri.org/IService/GetDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Descuento> GetDescuentoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateDescuento", ReplyAction="http://tempuri.org/IService/CreateDescuentoResponse")]
        TalycapGlobalData.Descuento CreateDescuento(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateDescuento", ReplyAction="http://tempuri.org/IService/CreateDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Descuento> CreateDescuentoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditDescuento", ReplyAction="http://tempuri.org/IService/EditDescuentoResponse")]
        TalycapGlobalData.Descuento EditDescuento(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditDescuento", ReplyAction="http://tempuri.org/IService/EditDescuentoResponse")]
        System.Threading.Tasks.Task<TalycapGlobalData.Descuento> EditDescuentoAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TalycapGlobalTestUnit.TalycapGlobalWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TalycapGlobalTestUnit.TalycapGlobalWCF.IService>, TalycapGlobalTestUnit.TalycapGlobalWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TalycapGlobalData.Descuento DeleteDescuento(string json) {
            return base.Channel.DeleteDescuento(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Descuento> DeleteDescuentoAsync(string json) {
            return base.Channel.DeleteDescuentoAsync(json);
        }
        
        public TalycapGlobalData.Operador[] ListaOperadores() {
            return base.Channel.ListaOperadores();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Operador[]> ListaOperadoresAsync() {
            return base.Channel.ListaOperadoresAsync();
        }
        
        public TalycapGlobalData.Operador GetOperador(int Id) {
            return base.Channel.GetOperador(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Operador> GetOperadorAsync(int Id) {
            return base.Channel.GetOperadorAsync(Id);
        }
        
        public TalycapGlobalData.Operador CreateOperador(string json) {
            return base.Channel.CreateOperador(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Operador> CreateOperadorAsync(string json) {
            return base.Channel.CreateOperadorAsync(json);
        }
        
        public TalycapGlobalData.Operador EditOperador(string json) {
            return base.Channel.EditOperador(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Operador> EditOperadorAsync(string json) {
            return base.Channel.EditOperadorAsync(json);
        }
        
        public TalycapGlobalData.Operador DeleteOperador(string json) {
            return base.Channel.DeleteOperador(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Operador> DeleteOperadorAsync(string json) {
            return base.Channel.DeleteOperadorAsync(json);
        }
        
        public TalycapGlobalData.Vehiculo[] ListaVehiculos() {
            return base.Channel.ListaVehiculos();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo[]> ListaVehiculosAsync() {
            return base.Channel.ListaVehiculosAsync();
        }
        
        public TalycapGlobalData.Vehiculo GetVehiculo(int Id) {
            return base.Channel.GetVehiculo(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> GetVehiculoAsync(int Id) {
            return base.Channel.GetVehiculoAsync(Id);
        }
        
        public TalycapGlobalData.Vehiculo CreateVehiculo(string json) {
            return base.Channel.CreateVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> CreateVehiculoAsync(string json) {
            return base.Channel.CreateVehiculoAsync(json);
        }
        
        public TalycapGlobalData.Vehiculo EditVehiculo(string json) {
            return base.Channel.EditVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> EditVehiculoAsync(string json) {
            return base.Channel.EditVehiculoAsync(json);
        }
        
        public TalycapGlobalData.Vehiculo DeleteVehiculo(string json) {
            return base.Channel.DeleteVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Vehiculo> DeleteVehiculoAsync(string json) {
            return base.Channel.DeleteVehiculoAsync(json);
        }
        
        public TalycapGlobalData.Guia[] ListaGuias() {
            return base.Channel.ListaGuias();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Guia[]> ListaGuiasAsync() {
            return base.Channel.ListaGuiasAsync();
        }
        
        public TalycapGlobalData.Guia GetGuia(int Id) {
            return base.Channel.GetGuia(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Guia> GetGuiaAsync(int Id) {
            return base.Channel.GetGuiaAsync(Id);
        }
        
        public TalycapGlobalData.Guia CreateGuia(string json) {
            return base.Channel.CreateGuia(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Guia> CreateGuiaAsync(string json) {
            return base.Channel.CreateGuiaAsync(json);
        }
        
        public TalycapGlobalData.Cliente[] ListaClientes() {
            return base.Channel.ListaClientes();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Cliente[]> ListaClientesAsync() {
            return base.Channel.ListaClientesAsync();
        }
        
        public TalycapGlobalData.Cliente GetCliente(int Id) {
            return base.Channel.GetCliente(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Cliente> GetClienteAsync(int Id) {
            return base.Channel.GetClienteAsync(Id);
        }
        
        public TalycapGlobalData.Cliente CreateCliente(string json) {
            return base.Channel.CreateCliente(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Cliente> CreateClienteAsync(string json) {
            return base.Channel.CreateClienteAsync(json);
        }
        
        public TalycapGlobalData.Cliente EditCliente(string json) {
            return base.Channel.EditCliente(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Cliente> EditClienteAsync(string json) {
            return base.Channel.EditClienteAsync(json);
        }
        
        public TalycapGlobalData.Cliente DeleteCliente(string json) {
            return base.Channel.DeleteCliente(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Cliente> DeleteClienteAsync(string json) {
            return base.Channel.DeleteClienteAsync(json);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType GetDataUsingDataContract(TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType> GetDataUsingDataContractAsync(TalycapGlobalTestUnit.TalycapGlobalWCF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public TalycapGlobalData.Pai[] ListaPaises() {
            return base.Channel.ListaPaises();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Pai[]> ListaPaisesAsync() {
            return base.Channel.ListaPaisesAsync();
        }
        
        public TalycapGlobalData.Pai GetPais(int Id) {
            return base.Channel.GetPais(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Pai> GetPaisAsync(int Id) {
            return base.Channel.GetPaisAsync(Id);
        }
        
        public TalycapGlobalData.Pai CreatePais(string json) {
            return base.Channel.CreatePais(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Pai> CreatePaisAsync(string json) {
            return base.Channel.CreatePaisAsync(json);
        }
        
        public TalycapGlobalData.Pai EditPais(string json) {
            return base.Channel.EditPais(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Pai> EditPaisAsync(string json) {
            return base.Channel.EditPaisAsync(json);
        }
        
        public TalycapGlobalData.Pai DeletePais(string json) {
            return base.Channel.DeletePais(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Pai> DeletePaisAsync(string json) {
            return base.Channel.DeletePaisAsync(json);
        }
        
        public TalycapGlobalData.Region[] ListaRegiones() {
            return base.Channel.ListaRegiones();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Region[]> ListaRegionesAsync() {
            return base.Channel.ListaRegionesAsync();
        }
        
        public TalycapGlobalData.Region GetRegion(int Id) {
            return base.Channel.GetRegion(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Region> GetRegionAsync(int Id) {
            return base.Channel.GetRegionAsync(Id);
        }
        
        public TalycapGlobalData.Region CreateRegion(string json) {
            return base.Channel.CreateRegion(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Region> CreateRegionAsync(string json) {
            return base.Channel.CreateRegionAsync(json);
        }
        
        public TalycapGlobalData.Region EditRegion(string json) {
            return base.Channel.EditRegion(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Region> EditRegionAsync(string json) {
            return base.Channel.EditRegionAsync(json);
        }
        
        public TalycapGlobalData.Region DeleteRegion(string json) {
            return base.Channel.DeleteRegion(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Region> DeleteRegionAsync(string json) {
            return base.Channel.DeleteRegionAsync(json);
        }
        
        public TalycapGlobalData.Ciudad[] ListaCiudades() {
            return base.Channel.ListaCiudades();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Ciudad[]> ListaCiudadesAsync() {
            return base.Channel.ListaCiudadesAsync();
        }
        
        public TalycapGlobalData.Ciudad GetCiudad(int Id) {
            return base.Channel.GetCiudad(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> GetCiudadAsync(int Id) {
            return base.Channel.GetCiudadAsync(Id);
        }
        
        public TalycapGlobalData.Ciudad CreateCiudad(string json) {
            return base.Channel.CreateCiudad(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> CreateCiudadAsync(string json) {
            return base.Channel.CreateCiudadAsync(json);
        }
        
        public TalycapGlobalData.Ciudad EditCiudad(string json) {
            return base.Channel.EditCiudad(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> EditCiudadAsync(string json) {
            return base.Channel.EditCiudadAsync(json);
        }
        
        public TalycapGlobalData.Ciudad DeleteCiudad(string json) {
            return base.Channel.DeleteCiudad(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Ciudad> DeleteCiudadAsync(string json) {
            return base.Channel.DeleteCiudadAsync(json);
        }
        
        public TalycapGlobalData.TipoAlmacen[] ListaTipoAlmacen() {
            return base.Channel.ListaTipoAlmacen();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen[]> ListaTipoAlmacenAsync() {
            return base.Channel.ListaTipoAlmacenAsync();
        }
        
        public TalycapGlobalData.TipoAlmacen GetTipoAlmacen(int Id) {
            return base.Channel.GetTipoAlmacen(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> GetTipoAlmacenAsync(int Id) {
            return base.Channel.GetTipoAlmacenAsync(Id);
        }
        
        public TalycapGlobalData.TipoAlmacen CreateTipoAlmacen(string json) {
            return base.Channel.CreateTipoAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> CreateTipoAlmacenAsync(string json) {
            return base.Channel.CreateTipoAlmacenAsync(json);
        }
        
        public TalycapGlobalData.TipoAlmacen EditTipoAlmacen(string json) {
            return base.Channel.EditTipoAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> EditTipoAlmacenAsync(string json) {
            return base.Channel.EditTipoAlmacenAsync(json);
        }
        
        public TalycapGlobalData.TipoAlmacen DeleteTipoAlmacen(string json) {
            return base.Channel.DeleteTipoAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoAlmacen> DeleteTipoAlmacenAsync(string json) {
            return base.Channel.DeleteTipoAlmacenAsync(json);
        }
        
        public TalycapGlobalData.TipoProducto[] ListaTipoProductos() {
            return base.Channel.ListaTipoProductos();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto[]> ListaTipoProductosAsync() {
            return base.Channel.ListaTipoProductosAsync();
        }
        
        public TalycapGlobalData.TipoProducto GetTipoProducto(int Id) {
            return base.Channel.GetTipoProducto(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> GetTipoProductoAsync(int Id) {
            return base.Channel.GetTipoProductoAsync(Id);
        }
        
        public TalycapGlobalData.TipoProducto CreateTipoProducto(string json) {
            return base.Channel.CreateTipoProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> CreateTipoProductoAsync(string json) {
            return base.Channel.CreateTipoProductoAsync(json);
        }
        
        public TalycapGlobalData.TipoProducto EditTipoProducto(string json) {
            return base.Channel.EditTipoProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> EditTipoProductoAsync(string json) {
            return base.Channel.EditTipoProductoAsync(json);
        }
        
        public TalycapGlobalData.TipoProducto DeleteTipoProducto(string json) {
            return base.Channel.DeleteTipoProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoProducto> DeleteTipoProductoAsync(string json) {
            return base.Channel.DeleteTipoProductoAsync(json);
        }
        
        public TalycapGlobalData.TipoEnvio[] ListaTipoEnvios() {
            return base.Channel.ListaTipoEnvios();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio[]> ListaTipoEnviosAsync() {
            return base.Channel.ListaTipoEnviosAsync();
        }
        
        public TalycapGlobalData.TipoEnvio GetTipoEnvio(int Id) {
            return base.Channel.GetTipoEnvio(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> GetTipoEnvioAsync(int Id) {
            return base.Channel.GetTipoEnvioAsync(Id);
        }
        
        public TalycapGlobalData.TipoEnvio CreateTipoEnvio(string json) {
            return base.Channel.CreateTipoEnvio(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> CreateTipoEnvioAsync(string json) {
            return base.Channel.CreateTipoEnvioAsync(json);
        }
        
        public TalycapGlobalData.TipoEnvio EditTipoEnvio(string json) {
            return base.Channel.EditTipoEnvio(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> EditTipoEnvioAsync(string json) {
            return base.Channel.EditTipoEnvioAsync(json);
        }
        
        public TalycapGlobalData.TipoEnvio DeleteTipoEnvio(string json) {
            return base.Channel.DeleteTipoEnvio(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoEnvio> DeleteTipoEnvioAsync(string json) {
            return base.Channel.DeleteTipoEnvioAsync(json);
        }
        
        public TalycapGlobalData.TipoDoc[] ListaTipoDocs() {
            return base.Channel.ListaTipoDocs();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc[]> ListaTipoDocsAsync() {
            return base.Channel.ListaTipoDocsAsync();
        }
        
        public TalycapGlobalData.TipoDoc GetTipoDoc(int Id) {
            return base.Channel.GetTipoDoc(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> GetTipoDocAsync(int Id) {
            return base.Channel.GetTipoDocAsync(Id);
        }
        
        public TalycapGlobalData.TipoDoc CreateTipoDoc(string json) {
            return base.Channel.CreateTipoDoc(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> CreateTipoDocAsync(string json) {
            return base.Channel.CreateTipoDocAsync(json);
        }
        
        public TalycapGlobalData.TipoDoc EditTipoDoc(string json) {
            return base.Channel.EditTipoDoc(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> EditTipoDocAsync(string json) {
            return base.Channel.EditTipoDocAsync(json);
        }
        
        public TalycapGlobalData.TipoDoc DeleteTipoDoc(string json) {
            return base.Channel.DeleteTipoDoc(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoDoc> DeleteTipoDocAsync(string json) {
            return base.Channel.DeleteTipoDocAsync(json);
        }
        
        public TalycapGlobalData.TipoVehiculo[] ListaTipoVehiculos() {
            return base.Channel.ListaTipoVehiculos();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo[]> ListaTipoVehiculosAsync() {
            return base.Channel.ListaTipoVehiculosAsync();
        }
        
        public TalycapGlobalData.TipoVehiculo GetTipoVehiculo(int Id) {
            return base.Channel.GetTipoVehiculo(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> GetTipoVehiculoAsync(int Id) {
            return base.Channel.GetTipoVehiculoAsync(Id);
        }
        
        public TalycapGlobalData.TipoVehiculo CreateTipoVehiculo(string json) {
            return base.Channel.CreateTipoVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> CreateTipoVehiculoAsync(string json) {
            return base.Channel.CreateTipoVehiculoAsync(json);
        }
        
        public TalycapGlobalData.TipoVehiculo EditTipoVehiculo(string json) {
            return base.Channel.EditTipoVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> EditTipoVehiculoAsync(string json) {
            return base.Channel.EditTipoVehiculoAsync(json);
        }
        
        public TalycapGlobalData.TipoVehiculo DeleteTipoVehiculo(string json) {
            return base.Channel.DeleteTipoVehiculo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.TipoVehiculo> DeleteTipoVehiculoAsync(string json) {
            return base.Channel.DeleteTipoVehiculoAsync(json);
        }
        
        public TalycapGlobalData.Estado[] ListaEstados() {
            return base.Channel.ListaEstados();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Estado[]> ListaEstadosAsync() {
            return base.Channel.ListaEstadosAsync();
        }
        
        public TalycapGlobalData.Estado GetEstado(int Id) {
            return base.Channel.GetEstado(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Estado> GetEstadoAsync(int Id) {
            return base.Channel.GetEstadoAsync(Id);
        }
        
        public TalycapGlobalData.Estado CreateEstado(string json) {
            return base.Channel.CreateEstado(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Estado> CreateEstadoAsync(string json) {
            return base.Channel.CreateEstadoAsync(json);
        }
        
        public TalycapGlobalData.Estado EditEstado(string json) {
            return base.Channel.EditEstado(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Estado> EditEstadoAsync(string json) {
            return base.Channel.EditEstadoAsync(json);
        }
        
        public TalycapGlobalData.Estado DeleteEstado(string json) {
            return base.Channel.DeleteEstado(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Estado> DeleteEstadoAsync(string json) {
            return base.Channel.DeleteEstadoAsync(json);
        }
        
        public TalycapGlobalData.ConsecutivoGuia GetConsecutivo(int TipoEnvioId) {
            return base.Channel.GetConsecutivo(TipoEnvioId);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> GetConsecutivoAsync(int TipoEnvioId) {
            return base.Channel.GetConsecutivoAsync(TipoEnvioId);
        }
        
        public TalycapGlobalData.ConsecutivoGuia CreateConsecutivo(string json) {
            return base.Channel.CreateConsecutivo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> CreateConsecutivoAsync(string json) {
            return base.Channel.CreateConsecutivoAsync(json);
        }
        
        public TalycapGlobalData.ConsecutivoGuia EditConsecutivo(string json) {
            return base.Channel.EditConsecutivo(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.ConsecutivoGuia> EditConsecutivoAsync(string json) {
            return base.Channel.EditConsecutivoAsync(json);
        }
        
        public TalycapGlobalData.Almacen[] ListaAlmacenes() {
            return base.Channel.ListaAlmacenes();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Almacen[]> ListaAlmacenesAsync() {
            return base.Channel.ListaAlmacenesAsync();
        }
        
        public TalycapGlobalData.Almacen GetAlmacen(int Id) {
            return base.Channel.GetAlmacen(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Almacen> GetAlmacenAsync(int Id) {
            return base.Channel.GetAlmacenAsync(Id);
        }
        
        public TalycapGlobalData.Almacen CreateAlmacen(string json) {
            return base.Channel.CreateAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Almacen> CreateAlmacenAsync(string json) {
            return base.Channel.CreateAlmacenAsync(json);
        }
        
        public TalycapGlobalData.Almacen EditAlmacen(string json) {
            return base.Channel.EditAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Almacen> EditAlmacenAsync(string json) {
            return base.Channel.EditAlmacenAsync(json);
        }
        
        public TalycapGlobalData.Almacen DeleteAlmacen(string json) {
            return base.Channel.DeleteAlmacen(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Almacen> DeleteAlmacenAsync(string json) {
            return base.Channel.DeleteAlmacenAsync(json);
        }
        
        public TalycapGlobalData.Producto[] ListaProductos() {
            return base.Channel.ListaProductos();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Producto[]> ListaProductosAsync() {
            return base.Channel.ListaProductosAsync();
        }
        
        public TalycapGlobalData.Producto GetProducto(int Id) {
            return base.Channel.GetProducto(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Producto> GetProductoAsync(int Id) {
            return base.Channel.GetProductoAsync(Id);
        }
        
        public TalycapGlobalData.Producto CreateProducto(string json) {
            return base.Channel.CreateProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Producto> CreateProductoAsync(string json) {
            return base.Channel.CreateProductoAsync(json);
        }
        
        public TalycapGlobalData.Producto EditProducto(string json) {
            return base.Channel.EditProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Producto> EditProductoAsync(string json) {
            return base.Channel.EditProductoAsync(json);
        }
        
        public TalycapGlobalData.Producto DeleteProducto(string json) {
            return base.Channel.DeleteProducto(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Producto> DeleteProductoAsync(string json) {
            return base.Channel.DeleteProductoAsync(json);
        }
        
        public TalycapGlobalData.Descuento[] ListaDescuentos() {
            return base.Channel.ListaDescuentos();
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Descuento[]> ListaDescuentosAsync() {
            return base.Channel.ListaDescuentosAsync();
        }
        
        public TalycapGlobalData.Descuento GetDescuento(int Id) {
            return base.Channel.GetDescuento(Id);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Descuento> GetDescuentoAsync(int Id) {
            return base.Channel.GetDescuentoAsync(Id);
        }
        
        public TalycapGlobalData.Descuento CreateDescuento(string json) {
            return base.Channel.CreateDescuento(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Descuento> CreateDescuentoAsync(string json) {
            return base.Channel.CreateDescuentoAsync(json);
        }
        
        public TalycapGlobalData.Descuento EditDescuento(string json) {
            return base.Channel.EditDescuento(json);
        }
        
        public System.Threading.Tasks.Task<TalycapGlobalData.Descuento> EditDescuentoAsync(string json) {
            return base.Channel.EditDescuentoAsync(json);
        }
    }
}
